# Generated by Django 5.0.6 on 2024-05-24 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='sent', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_request_creator', to=settings.AUTH_USER_MODEL, verbose_name='Request author')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_request_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Request recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles_pictures/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG'])], verbose_name='Picture')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profiles_pictures/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG'])], verbose_name='Banner')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('age', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Age')),
                ('friends', models.ManyToManyField(blank=True, related_name='frends', to=settings.AUTH_USER_MODEL, verbose_name='Друзья')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
